export const CREATE_USER = 'USER/CREATE_USER';
export const LOAD_USER = 'USER/LOAD_USER';
export const LOAD_USERS = 'USER/LOAD_USERS';
export const CLEAR_USERS = 'USER/CLEAR_USERS';
export const DELETE_USER = 'USER/DELETE_USER';

export const CREATE_POST = 'POST/CREATE_POST';
export const LOAD_POST = 'POST/LOAD_POST';
export const LOAD_POSTS = 'POST/LOAD_POSTS';

export const CREATE_ALBUM = 'ALBUM/CREATE_ALBUM';
export const LOAD_ALBUN = 'ALBUM/LOAD_ALBUM';
export const LOAD_ALBUMS = 'ALBUM/LOAD_ALBUMS';