export const CREATE_USER = 'USER/CREATE_USER';
export const LOAD_USERS = 'USER/LOAD_USERS';
export const CLEAR_USERS = 'USER/CLEAR_USERS';
export const DELETE_USER = 'USER/DELETE_USER';
export const SET_USER_CURRENT_PAGE = 'USER/SET_CURRENT_PAGE';


export const CREATE_POST = 'POST/CREATE_POST';
export const LOAD_POST = 'POST/LOAD_POST';
export const LOAD_POSTS = 'POST/LOAD_POSTS';
export const UPDATE_POST = 'POST/UPDATE_POST';
export const CLEAR_POSTS = 'POST/CLEAR_POSTS';
export const SET_POST_CURRENT_PAGE = 'POST/SET_CURRENT_PAGE';

export const CREATE_COMMENT = 'COMMENT/CREATE_COMMENT';
export const LOAD_COMMENTS = 'COMMENT/LOAD_COMMENTS';
export const FILTER_COMMENTS = 'COMMENT/FILTER_COMMENTS';

export const CREATE_ALBUM = 'ALBUM/CREATE_ALBUM';
export const LOAD_ALBUM = 'ALBUM/LOAD_ALBUM';
export const LOAD_ALBUMS = 'ALBUM/LOAD_ALBUMS';
export const SET_ALBUM_CURRENT_PAGE = 'ALBUM/SET_CURRENT_PAGE';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
export const ENABLE_BUTTONS = 'APP/ENABLE_BUTTONS';
export const DISABLE_BUTTONS = 'APP/DISBLE_BUTTONS';

export const LOAD_NEWS = 'NEWS/LOAD_NEWS';
export const CREATE_NEWS = 'NEWS/CREATE_NEWS';
export const SET_NEWS_CURRENT_PAGE = 'NEWS/SET_CURRENT_PAGE';

export const FILTER_USER = 'FILTER/FILTER_USER';
export const FILTER_POSTS = 'FILTER/FILTER_POSTS';
export const FILTER_ALBUMS = 'FILTER/FILTER_ALBUMS';

export const REFRESH_USER_LIST ='CHAT/REFRESH_USER_LIST';




