export const CREATE_USER = 'USER/CREATE_USER';
export const LOAD_USER = 'USER/LOAD_USER';
export const LOAD_USERS = 'USER/LOAD_USERS';
export const CLEAR_USERS = 'USER/CLEAR_USERS';
export const DELETE_USER = 'USER/DELETE_USER';
export const FILTER_USERS = 'USER/FILTER_USERS';

export const CREATE_POST = 'POST/CREATE_POST';
export const LOAD_POST = 'POST/LOAD_POST';
export const LOAD_POSTS = 'POST/LOAD_POSTS';
export const UPDATE_POST = 'POST/UPDATE_POST';
export const CLEAR_POSTS = 'POST/CLEAR_POSTS';
export const FILTER_POSTS = 'POST/FILTER_POSTS';

export const CREATE_COMMENT = 'COMMENT/CREATE_COMMENT';
export const LOAD_COMMENTS = 'COMMENT/LOAD_COMMENTS';
export const FILTER_COMMENTS = 'COMMENT/FILTER_COMMENTS';

export const CREATE_ALBUM = 'ALBUM/CREATE_ALBUM';
export const LOAD_ALBUN = 'ALBUM/LOAD_ALBUM';
export const LOAD_ALBUMS = 'ALBUM/LOAD_ALBUMS';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
export const ENABLE_BUTTONS = 'APP/ENABLE_BUTTONS';
export const DISABLE_BUTTONS = 'APP/DISBLE_BUTTONS';
